### ISSUE TITLE
Error in accelerate data_loader "multiprocessing_context"

### ISSUE THREAD

**Issue by jesusGS01** [lucidrains/denoising-diffusion-pytorch#350]
I am trying the following code in my Docker container:

``` 
model = Unet(
        dim = 64,
        dim_mults = (1, 2, 4, 8),
        flash_attn = True
    )
    
    diffusion = GaussianDiffusion(
        model,
        image_size = 512,
        timesteps = 1000,           # number of steps
        sampling_timesteps = 250    # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
    )
    
    trainer = Trainer(
        diffusion,
        '/images_DDPM',
        train_batch_size = 8,
        train_lr = 8e-5,
        train_num_steps = 700000,         # total training steps
        gradient_accumulate_every = 2,    # gradient accumulation steps
        ema_decay = 0.995,                # exponential moving average decay
        amp = True,                       # turn on mixed precision
        calculate_fid = True,              # whether to calculate fid during training
        save_best_and_latest_only = True,
        results_folder = "/app/resultsDDPM"
    )
    
    trainer.train()
```

However, I got the following error: 

```
A100 GPU detected, using flash attention if input tensor is on cuda
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Traceback (most recent call last):
  File "/app/MIDOGpp-main/main.py", line 43, in <module>
    training_DDPM(cfg)
  File "/app/MIDOGpp-main/training_DDPM.py", line 41, in training_DDPM
    trainer = Trainer(
              ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/denoising_diffusion_pytorch/denoising_diffusion_pytorch.py", line 949, in __init__
    dl = self.accelerator.prepare(dl)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/accelerator.py", line 1329, in prepare
    result = tuple(
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/accelerator.py", line 1330, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/accelerator.py", line 1203, in _prepare_one
    return self.prepare_data_loader(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/accelerator.py", line 2105, in prepare_data_loader
    prepared_data_loader = prepare_data_loader(
                           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/data_loader.py", line 1163, in prepare_data_loader
    dataloader = DataLoaderShard(
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/data_loader.py", line 533, in __init__
    super().__init__(dataset, use_stateful_dataloader=use_stateful_dataloader, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/accelerate/data_loader.py", line 419, in __init__
    self.base_dataloader = DataLoader(dataset, batch_sampler=batch_sampler, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: intercept_args() got an unexpected keyword argument 'multiprocessing_context'
```

I am using a NVIDIA 4090 GPU.
Has anyone found a solution to this problem?

Best regards

**Comment by MADAO-King** [comment]
Try adding 'if __name__=='__main__' before your code: '

**Comment by jesusGS01** [comment]
> Try adding 'if **name**=='**main**' before your code: '

It worked, thanks.
